# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'

describe 'essential test' do

  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'correct data side: server' do
    @driver.get('http://localhost:3001/proxy/input')
    @driver.find_element(:id, 'number').click
    @driver.find_element(:id, 'number').send_keys('1000')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tbody th:nth-child(2)').text).to eq('220')
    expect(@driver.find_element(:css, 'tbody th:nth-child(3)').text).to eq('284')
    expect(@driver.find_element(:css, 'tbody th:nth-child(1)').text).to eq('1')
    sleep 2
  end

  it 'correct data side: client-with-xslt' do
    @driver.get('http://localhost:3001/proxy/input')
    @driver.find_element(:id, 'number').click
    @driver.find_element(:id, 'number').send_keys('1500')
    @driver.find_element(:css, '.form-check:nth-child(4) > .form-check-label').click
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'tbody:nth-child(2) th:nth-child(2)').text).to eq('220')
    expect(@driver.find_element(:css, 'tbody:nth-child(2) th:nth-child(3)').text).to eq('284')
    expect(@driver.find_element(:css, 'tbody:nth-child(3) th:nth-child(2)').text).to eq('1184')
    expect(@driver.find_element(:css, 'tbody:nth-child(3) th:nth-child(3)').text).to eq('1210')
    sleep 2
  end

  it 'incorrect data side: server' do
    @driver.get('http://localhost:3001/proxy/input')
    @driver.find_element(:id, 'number').click
    @driver.find_element(:id, 'number').send_keys('gsdfg')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:css, 'p').text).to eq('Неверный параметр запроса (n = 0)')
    sleep 2
  end

  it 'no result side: server' do
    @driver.get('http://localhost:3001/proxy/input')
    @driver.find_element(:id, 'number').click
    @driver.find_element(:id, 'number').send_keys('100')
    @driver.find_element(:css, '.form-group:nth-child(2)').click
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.container').click
    expect(@driver.find_element(:css, 'p').text).to eq('Дружественных числе в промежутке от 1 до n не сущесвует (n = 100)')
    sleep 2
  end

  it 'correct data side: client' do
    @driver.get('http://localhost:3001/proxy/input')
    @driver.find_element(:css, '.form-check:nth-child(3) > .form-check-label').click
    @driver.find_element(:id, 'number').click
    @driver.find_element(:id, 'number').send_keys('1000')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:xpath, '//array/array[1]').text).to eq('220')
    expect(@driver.find_element(:xpath, '//array/array[2]').text).to eq('284')
    sleep 2
  end
end
